AlignParameters:
  Enabled: false
AndOr:
  Enabled: false
CaseEquality:
  Enabled: false
Documentation:
  Enabled: false
EndAlignment:
  AlignWith: variable
LineLength:
  Max: 100
RescueException:
  Enabled: false
SignalException:
  Enabled: false
StringLiterals:
  EnforcedStyle: double_quotes
TrailingComma:
  Enabled: false
TrivialAccessors:
  AllowPredicates: true
